### ISSUE TITLE
install error  when  reload nginx

### ISSUE THREAD

**Issue by guanhui07** [saks/lua-resty-repl#20]
/usr/local/openresty/lualib/resty/repl/formatter.lua:1: module 'inspect' not found:
	no field package.preload['inspect']
	no file '/data1/inspect.lua'

**Comment by guanhui07** [comment]
i add path in  lua path   but  error   in  error.log
`2016/11/27 16:58:58 [alert] 73107#0: setrlimit(RLIMIT_NOFILE, 65535) failed (22: Invalid argument)
2016/11/27 16:58:58 [alert] 73108#0: setrlimit(RLIMIT_NOFILE, 65535) failed (22: Invalid argument)`

run  a  request

**Comment by saks** [comment]
Could you provide more details about your way to install repl package?

**Comment by guanhui07** [comment]
thx , that is work

**Comment by guanhui07** [comment]
https://github.com/saks/lua-resty-repl/tree/master/vendor
